package io.oss.protocol.protobuf.pbfile;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PortoBufProtocol.proto

public final class ProtoBufProtocol {
  private ProtoBufProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FileCommandOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FileCommand)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .FileCommand.Header header = 1;</code>
     */
    java.util.List<FileCommand.Header>
        getHeaderList();
    /**
     * <code>repeated .FileCommand.Header header = 1;</code>
     */
    ProtoBufProtocol.FileCommand.Header getHeader(int index);
    /**
     * <code>repeated .FileCommand.Header header = 1;</code>
     */
    int getHeaderCount();
    /**
     * <code>repeated .FileCommand.Header header = 1;</code>
     */
    java.util.List<? extends FileCommand.HeaderOrBuilder>
        getHeaderOrBuilderList();
    /**
     * <code>repeated .FileCommand.Header header = 1;</code>
     */
    ProtoBufProtocol.FileCommand.HeaderOrBuilder getHeaderOrBuilder(
            int index);

    /**
     * <code>repeated .FileCommand.Body body = 2;</code>
     */
    java.util.List<FileCommand.Body>
        getBodyList();
    /**
     * <code>repeated .FileCommand.Body body = 2;</code>
     */
    ProtoBufProtocol.FileCommand.Body getBody(int index);
    /**
     * <code>repeated .FileCommand.Body body = 2;</code>
     */
    int getBodyCount();
    /**
     * <code>repeated .FileCommand.Body body = 2;</code>
     */
    java.util.List<? extends FileCommand.BodyOrBuilder>
        getBodyOrBuilderList();
    /**
     * <code>repeated .FileCommand.Body body = 2;</code>
     */
    ProtoBufProtocol.FileCommand.BodyOrBuilder getBodyOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code FileCommand}
   */
  public  static final class FileCommand extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:FileCommand)
      FileCommandOrBuilder {
    // Use FileCommand.newBuilder() to construct.
    private FileCommand(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FileCommand() {
      header_ = java.util.Collections.emptyList();
      body_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private FileCommand(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                header_ = new java.util.ArrayList<Header>();
                mutable_bitField0_ |= 0x00000001;
              }
              header_.add(
                  input.readMessage(ProtoBufProtocol.FileCommand.Header.parser(), extensionRegistry));
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                body_ = new java.util.ArrayList<Body>();
                mutable_bitField0_ |= 0x00000002;
              }
              body_.add(
                  input.readMessage(ProtoBufProtocol.FileCommand.Body.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          header_ = java.util.Collections.unmodifiableList(header_);
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          body_ = java.util.Collections.unmodifiableList(body_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoBufProtocol.internal_static_FileCommand_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoBufProtocol.internal_static_FileCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProtoBufProtocol.FileCommand.class, ProtoBufProtocol.FileCommand.Builder.class);
    }

    public interface HeaderOrBuilder extends
        // @@protoc_insertion_point(interface_extends:FileCommand.Header)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string uri = 1;</code>
       */
      String getUri();
      /**
       * <code>string uri = 1;</code>
       */
      com.google.protobuf.ByteString
          getUriBytes();

      /**
       * <code>int32 seq = 2;</code>
       */
      int getSeq();

      /**
       * <code>string accessToken = 3;</code>
       */
      String getAccessToken();
      /**
       * <code>string accessToken = 3;</code>
       */
      com.google.protobuf.ByteString
          getAccessTokenBytes();
    }
    /**
     * Protobuf type {@code FileCommand.Header}
     */
    public  static final class Header extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:FileCommand.Header)
        HeaderOrBuilder {
      // Use Header.newBuilder() to construct.
      private Header(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Header() {
        uri_ = "";
        seq_ = 0;
        accessToken_ = "";
      }

      @Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
      }
      private Header(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                String s = input.readStringRequireUtf8();

                uri_ = s;
                break;
              }
              case 16: {

                seq_ = input.readInt32();
                break;
              }
              case 26: {
                String s = input.readStringRequireUtf8();

                accessToken_ = s;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoBufProtocol.internal_static_FileCommand_Header_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoBufProtocol.internal_static_FileCommand_Header_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtoBufProtocol.FileCommand.Header.class, ProtoBufProtocol.FileCommand.Header.Builder.class);
      }

      public static final int URI_FIELD_NUMBER = 1;
      private volatile Object uri_;
      /**
       * <code>string uri = 1;</code>
       */
      public String getUri() {
        Object ref = uri_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          uri_ = s;
          return s;
        }
      }
      /**
       * <code>string uri = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUriBytes() {
        Object ref = uri_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          uri_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int SEQ_FIELD_NUMBER = 2;
      private int seq_;
      /**
       * <code>int32 seq = 2;</code>
       */
      public int getSeq() {
        return seq_;
      }

      public static final int ACCESSTOKEN_FIELD_NUMBER = 3;
      private volatile Object accessToken_;
      /**
       * <code>string accessToken = 3;</code>
       */
      public String getAccessToken() {
        Object ref = accessToken_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          accessToken_ = s;
          return s;
        }
      }
      /**
       * <code>string accessToken = 3;</code>
       */
      public com.google.protobuf.ByteString
          getAccessTokenBytes() {
        Object ref = accessToken_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          accessToken_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getUriBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uri_);
        }
        if (seq_ != 0) {
          output.writeInt32(2, seq_);
        }
        if (!getAccessTokenBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 3, accessToken_);
        }
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getUriBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uri_);
        }
        if (seq_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, seq_);
        }
        if (!getAccessTokenBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, accessToken_);
        }
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @Override
      public boolean equals(final Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof ProtoBufProtocol.FileCommand.Header)) {
          return super.equals(obj);
        }
        ProtoBufProtocol.FileCommand.Header other = (ProtoBufProtocol.FileCommand.Header) obj;

        boolean result = true;
        result = result && getUri()
            .equals(other.getUri());
        result = result && (getSeq()
            == other.getSeq());
        result = result && getAccessToken()
            .equals(other.getAccessToken());
        return result;
      }

      @Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + URI_FIELD_NUMBER;
        hash = (53 * hash) + getUri().hashCode();
        hash = (37 * hash) + SEQ_FIELD_NUMBER;
        hash = (53 * hash) + getSeq();
        hash = (37 * hash) + ACCESSTOKEN_FIELD_NUMBER;
        hash = (53 * hash) + getAccessToken().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static ProtoBufProtocol.FileCommand.Header parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ProtoBufProtocol.FileCommand.Header parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ProtoBufProtocol.FileCommand.Header parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ProtoBufProtocol.FileCommand.Header parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ProtoBufProtocol.FileCommand.Header parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ProtoBufProtocol.FileCommand.Header parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ProtoBufProtocol.FileCommand.Header parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static ProtoBufProtocol.FileCommand.Header parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static ProtoBufProtocol.FileCommand.Header parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static ProtoBufProtocol.FileCommand.Header parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static ProtoBufProtocol.FileCommand.Header parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static ProtoBufProtocol.FileCommand.Header parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(ProtoBufProtocol.FileCommand.Header prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code FileCommand.Header}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:FileCommand.Header)
          ProtoBufProtocol.FileCommand.HeaderOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return ProtoBufProtocol.internal_static_FileCommand_Header_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return ProtoBufProtocol.internal_static_FileCommand_Header_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  ProtoBufProtocol.FileCommand.Header.class, ProtoBufProtocol.FileCommand.Header.Builder.class);
        }

        // Construct using PortoBufProtocol.FileCommand.Header.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          uri_ = "";

          seq_ = 0;

          accessToken_ = "";

          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return ProtoBufProtocol.internal_static_FileCommand_Header_descriptor;
        }

        public ProtoBufProtocol.FileCommand.Header getDefaultInstanceForType() {
          return ProtoBufProtocol.FileCommand.Header.getDefaultInstance();
        }

        public ProtoBufProtocol.FileCommand.Header build() {
          ProtoBufProtocol.FileCommand.Header result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public ProtoBufProtocol.FileCommand.Header buildPartial() {
          ProtoBufProtocol.FileCommand.Header result = new ProtoBufProtocol.FileCommand.Header(this);
          result.uri_ = uri_;
          result.seq_ = seq_;
          result.accessToken_ = accessToken_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof ProtoBufProtocol.FileCommand.Header) {
            return mergeFrom((ProtoBufProtocol.FileCommand.Header)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(ProtoBufProtocol.FileCommand.Header other) {
          if (other == ProtoBufProtocol.FileCommand.Header.getDefaultInstance()) return this;
          if (!other.getUri().isEmpty()) {
            uri_ = other.uri_;
            onChanged();
          }
          if (other.getSeq() != 0) {
            setSeq(other.getSeq());
          }
          if (!other.getAccessToken().isEmpty()) {
            accessToken_ = other.accessToken_;
            onChanged();
          }
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          ProtoBufProtocol.FileCommand.Header parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (ProtoBufProtocol.FileCommand.Header) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private Object uri_ = "";
        /**
         * <code>string uri = 1;</code>
         */
        public String getUri() {
          Object ref = uri_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            uri_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>string uri = 1;</code>
         */
        public com.google.protobuf.ByteString
            getUriBytes() {
          Object ref = uri_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            uri_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string uri = 1;</code>
         */
        public Builder setUri(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }

          uri_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string uri = 1;</code>
         */
        public Builder clearUri() {

          uri_ = getDefaultInstance().getUri();
          onChanged();
          return this;
        }
        /**
         * <code>string uri = 1;</code>
         */
        public Builder setUriBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

          uri_ = value;
          onChanged();
          return this;
        }

        private int seq_ ;
        /**
         * <code>int32 seq = 2;</code>
         */
        public int getSeq() {
          return seq_;
        }
        /**
         * <code>int32 seq = 2;</code>
         */
        public Builder setSeq(int value) {

          seq_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 seq = 2;</code>
         */
        public Builder clearSeq() {

          seq_ = 0;
          onChanged();
          return this;
        }

        private Object accessToken_ = "";
        /**
         * <code>string accessToken = 3;</code>
         */
        public String getAccessToken() {
          Object ref = accessToken_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            accessToken_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>string accessToken = 3;</code>
         */
        public com.google.protobuf.ByteString
            getAccessTokenBytes() {
          Object ref = accessToken_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            accessToken_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string accessToken = 3;</code>
         */
        public Builder setAccessToken(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }

          accessToken_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string accessToken = 3;</code>
         */
        public Builder clearAccessToken() {

          accessToken_ = getDefaultInstance().getAccessToken();
          onChanged();
          return this;
        }
        /**
         * <code>string accessToken = 3;</code>
         */
        public Builder setAccessTokenBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

          accessToken_ = value;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }


        // @@protoc_insertion_point(builder_scope:FileCommand.Header)
      }

      // @@protoc_insertion_point(class_scope:FileCommand.Header)
      private static final ProtoBufProtocol.FileCommand.Header DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new ProtoBufProtocol.FileCommand.Header();
      }

      public static ProtoBufProtocol.FileCommand.Header getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Header>
          PARSER = new com.google.protobuf.AbstractParser<Header>() {
        public Header parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new Header(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Header> parser() {
        return PARSER;
      }

      @Override
      public com.google.protobuf.Parser<Header> getParserForType() {
        return PARSER;
      }

      public ProtoBufProtocol.FileCommand.Header getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public interface BodyOrBuilder extends
        // @@protoc_insertion_point(interface_extends:FileCommand.Body)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>bytes buffer = 1;</code>
       */
      com.google.protobuf.ByteString getBuffer();

      /**
       * <code>string resp = 2;</code>
       */
      String getResp();
      /**
       * <code>string resp = 2;</code>
       */
      com.google.protobuf.ByteString
          getRespBytes();
    }
    /**
     * Protobuf type {@code FileCommand.Body}
     */
    public  static final class Body extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:FileCommand.Body)
        BodyOrBuilder {
      // Use Body.newBuilder() to construct.
      private Body(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Body() {
        buffer_ = com.google.protobuf.ByteString.EMPTY;
        resp_ = "";
      }

      @Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
      }
      private Body(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {

                buffer_ = input.readBytes();
                break;
              }
              case 18: {
                String s = input.readStringRequireUtf8();

                resp_ = s;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoBufProtocol.internal_static_FileCommand_Body_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoBufProtocol.internal_static_FileCommand_Body_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtoBufProtocol.FileCommand.Body.class, ProtoBufProtocol.FileCommand.Body.Builder.class);
      }

      public static final int BUFFER_FIELD_NUMBER = 1;
      private com.google.protobuf.ByteString buffer_;
      /**
       * <code>bytes buffer = 1;</code>
       */
      public com.google.protobuf.ByteString getBuffer() {
        return buffer_;
      }

      public static final int RESP_FIELD_NUMBER = 2;
      private volatile Object resp_;
      /**
       * <code>string resp = 2;</code>
       */
      public String getResp() {
        Object ref = resp_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          resp_ = s;
          return s;
        }
      }
      /**
       * <code>string resp = 2;</code>
       */
      public com.google.protobuf.ByteString
          getRespBytes() {
        Object ref = resp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          resp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!buffer_.isEmpty()) {
          output.writeBytes(1, buffer_);
        }
        if (!getRespBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, resp_);
        }
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!buffer_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, buffer_);
        }
        if (!getRespBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, resp_);
        }
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @Override
      public boolean equals(final Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof ProtoBufProtocol.FileCommand.Body)) {
          return super.equals(obj);
        }
        ProtoBufProtocol.FileCommand.Body other = (ProtoBufProtocol.FileCommand.Body) obj;

        boolean result = true;
        result = result && getBuffer()
            .equals(other.getBuffer());
        result = result && getResp()
            .equals(other.getResp());
        return result;
      }

      @Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + BUFFER_FIELD_NUMBER;
        hash = (53 * hash) + getBuffer().hashCode();
        hash = (37 * hash) + RESP_FIELD_NUMBER;
        hash = (53 * hash) + getResp().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static ProtoBufProtocol.FileCommand.Body parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ProtoBufProtocol.FileCommand.Body parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ProtoBufProtocol.FileCommand.Body parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ProtoBufProtocol.FileCommand.Body parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ProtoBufProtocol.FileCommand.Body parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ProtoBufProtocol.FileCommand.Body parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ProtoBufProtocol.FileCommand.Body parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static ProtoBufProtocol.FileCommand.Body parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static ProtoBufProtocol.FileCommand.Body parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static ProtoBufProtocol.FileCommand.Body parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static ProtoBufProtocol.FileCommand.Body parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static ProtoBufProtocol.FileCommand.Body parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(ProtoBufProtocol.FileCommand.Body prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code FileCommand.Body}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:FileCommand.Body)
          ProtoBufProtocol.FileCommand.BodyOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return ProtoBufProtocol.internal_static_FileCommand_Body_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return ProtoBufProtocol.internal_static_FileCommand_Body_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  ProtoBufProtocol.FileCommand.Body.class, ProtoBufProtocol.FileCommand.Body.Builder.class);
        }

        // Construct using PortoBufProtocol.FileCommand.Body.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          buffer_ = com.google.protobuf.ByteString.EMPTY;

          resp_ = "";

          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return ProtoBufProtocol.internal_static_FileCommand_Body_descriptor;
        }

        public ProtoBufProtocol.FileCommand.Body getDefaultInstanceForType() {
          return ProtoBufProtocol.FileCommand.Body.getDefaultInstance();
        }

        public ProtoBufProtocol.FileCommand.Body build() {
          ProtoBufProtocol.FileCommand.Body result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public ProtoBufProtocol.FileCommand.Body buildPartial() {
          ProtoBufProtocol.FileCommand.Body result = new ProtoBufProtocol.FileCommand.Body(this);
          result.buffer_ = buffer_;
          result.resp_ = resp_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof ProtoBufProtocol.FileCommand.Body) {
            return mergeFrom((ProtoBufProtocol.FileCommand.Body)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(ProtoBufProtocol.FileCommand.Body other) {
          if (other == ProtoBufProtocol.FileCommand.Body.getDefaultInstance()) return this;
          if (other.getBuffer() != com.google.protobuf.ByteString.EMPTY) {
            setBuffer(other.getBuffer());
          }
          if (!other.getResp().isEmpty()) {
            resp_ = other.resp_;
            onChanged();
          }
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          ProtoBufProtocol.FileCommand.Body parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (ProtoBufProtocol.FileCommand.Body) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private com.google.protobuf.ByteString buffer_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>bytes buffer = 1;</code>
         */
        public com.google.protobuf.ByteString getBuffer() {
          return buffer_;
        }
        /**
         * <code>bytes buffer = 1;</code>
         */
        public Builder setBuffer(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }

          buffer_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>bytes buffer = 1;</code>
         */
        public Builder clearBuffer() {

          buffer_ = getDefaultInstance().getBuffer();
          onChanged();
          return this;
        }

        private Object resp_ = "";
        /**
         * <code>string resp = 2;</code>
         */
        public String getResp() {
          Object ref = resp_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            resp_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>string resp = 2;</code>
         */
        public com.google.protobuf.ByteString
            getRespBytes() {
          Object ref = resp_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            resp_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string resp = 2;</code>
         */
        public Builder setResp(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }

          resp_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string resp = 2;</code>
         */
        public Builder clearResp() {

          resp_ = getDefaultInstance().getResp();
          onChanged();
          return this;
        }
        /**
         * <code>string resp = 2;</code>
         */
        public Builder setRespBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

          resp_ = value;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }


        // @@protoc_insertion_point(builder_scope:FileCommand.Body)
      }

      // @@protoc_insertion_point(class_scope:FileCommand.Body)
      private static final ProtoBufProtocol.FileCommand.Body DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new ProtoBufProtocol.FileCommand.Body();
      }

      public static ProtoBufProtocol.FileCommand.Body getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Body>
          PARSER = new com.google.protobuf.AbstractParser<Body>() {
        public Body parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new Body(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Body> parser() {
        return PARSER;
      }

      @Override
      public com.google.protobuf.Parser<Body> getParserForType() {
        return PARSER;
      }

      public ProtoBufProtocol.FileCommand.Body getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int HEADER_FIELD_NUMBER = 1;
    private java.util.List<Header> header_;
    /**
     * <code>repeated .FileCommand.Header header = 1;</code>
     */
    public java.util.List<Header> getHeaderList() {
      return header_;
    }
    /**
     * <code>repeated .FileCommand.Header header = 1;</code>
     */
    public java.util.List<? extends HeaderOrBuilder>
        getHeaderOrBuilderList() {
      return header_;
    }
    /**
     * <code>repeated .FileCommand.Header header = 1;</code>
     */
    public int getHeaderCount() {
      return header_.size();
    }
    /**
     * <code>repeated .FileCommand.Header header = 1;</code>
     */
    public ProtoBufProtocol.FileCommand.Header getHeader(int index) {
      return header_.get(index);
    }
    /**
     * <code>repeated .FileCommand.Header header = 1;</code>
     */
    public ProtoBufProtocol.FileCommand.HeaderOrBuilder getHeaderOrBuilder(
        int index) {
      return header_.get(index);
    }

    public static final int BODY_FIELD_NUMBER = 2;
    private java.util.List<Body> body_;
    /**
     * <code>repeated .FileCommand.Body body = 2;</code>
     */
    public java.util.List<Body> getBodyList() {
      return body_;
    }
    /**
     * <code>repeated .FileCommand.Body body = 2;</code>
     */
    public java.util.List<? extends BodyOrBuilder>
        getBodyOrBuilderList() {
      return body_;
    }
    /**
     * <code>repeated .FileCommand.Body body = 2;</code>
     */
    public int getBodyCount() {
      return body_.size();
    }
    /**
     * <code>repeated .FileCommand.Body body = 2;</code>
     */
    public ProtoBufProtocol.FileCommand.Body getBody(int index) {
      return body_.get(index);
    }
    /**
     * <code>repeated .FileCommand.Body body = 2;</code>
     */
    public ProtoBufProtocol.FileCommand.BodyOrBuilder getBodyOrBuilder(
        int index) {
      return body_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < header_.size(); i++) {
        output.writeMessage(1, header_.get(i));
      }
      for (int i = 0; i < body_.size(); i++) {
        output.writeMessage(2, body_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < header_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, header_.get(i));
      }
      for (int i = 0; i < body_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, body_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ProtoBufProtocol.FileCommand)) {
        return super.equals(obj);
      }
      ProtoBufProtocol.FileCommand other = (ProtoBufProtocol.FileCommand) obj;

      boolean result = true;
      result = result && getHeaderList()
          .equals(other.getHeaderList());
      result = result && getBodyList()
          .equals(other.getBodyList());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getHeaderCount() > 0) {
        hash = (37 * hash) + HEADER_FIELD_NUMBER;
        hash = (53 * hash) + getHeaderList().hashCode();
      }
      if (getBodyCount() > 0) {
        hash = (37 * hash) + BODY_FIELD_NUMBER;
        hash = (53 * hash) + getBodyList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ProtoBufProtocol.FileCommand parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoBufProtocol.FileCommand parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoBufProtocol.FileCommand parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoBufProtocol.FileCommand parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoBufProtocol.FileCommand parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoBufProtocol.FileCommand parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoBufProtocol.FileCommand parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtoBufProtocol.FileCommand parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtoBufProtocol.FileCommand parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ProtoBufProtocol.FileCommand parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtoBufProtocol.FileCommand parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtoBufProtocol.FileCommand parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ProtoBufProtocol.FileCommand prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FileCommand}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FileCommand)
        ProtoBufProtocol.FileCommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoBufProtocol.internal_static_FileCommand_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoBufProtocol.internal_static_FileCommand_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtoBufProtocol.FileCommand.class, ProtoBufProtocol.FileCommand.Builder.class);
      }

      // Construct using PortoBufProtocol.FileCommand.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getHeaderFieldBuilder();
          getBodyFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          headerBuilder_.clear();
        }
        if (bodyBuilder_ == null) {
          body_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          bodyBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoBufProtocol.internal_static_FileCommand_descriptor;
      }

      public ProtoBufProtocol.FileCommand getDefaultInstanceForType() {
        return ProtoBufProtocol.FileCommand.getDefaultInstance();
      }

      public ProtoBufProtocol.FileCommand build() {
        ProtoBufProtocol.FileCommand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ProtoBufProtocol.FileCommand buildPartial() {
        ProtoBufProtocol.FileCommand result = new ProtoBufProtocol.FileCommand(this);
        int from_bitField0_ = bitField0_;
        if (headerBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            header_ = java.util.Collections.unmodifiableList(header_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.header_ = header_;
        } else {
          result.header_ = headerBuilder_.build();
        }
        if (bodyBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            body_ = java.util.Collections.unmodifiableList(body_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.body_ = body_;
        } else {
          result.body_ = bodyBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtoBufProtocol.FileCommand) {
          return mergeFrom((ProtoBufProtocol.FileCommand)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProtoBufProtocol.FileCommand other) {
        if (other == ProtoBufProtocol.FileCommand.getDefaultInstance()) return this;
        if (headerBuilder_ == null) {
          if (!other.header_.isEmpty()) {
            if (header_.isEmpty()) {
              header_ = other.header_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureHeaderIsMutable();
              header_.addAll(other.header_);
            }
            onChanged();
          }
        } else {
          if (!other.header_.isEmpty()) {
            if (headerBuilder_.isEmpty()) {
              headerBuilder_.dispose();
              headerBuilder_ = null;
              header_ = other.header_;
              bitField0_ = (bitField0_ & ~0x00000001);
              headerBuilder_ =
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getHeaderFieldBuilder() : null;
            } else {
              headerBuilder_.addAllMessages(other.header_);
            }
          }
        }
        if (bodyBuilder_ == null) {
          if (!other.body_.isEmpty()) {
            if (body_.isEmpty()) {
              body_ = other.body_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureBodyIsMutable();
              body_.addAll(other.body_);
            }
            onChanged();
          }
        } else {
          if (!other.body_.isEmpty()) {
            if (bodyBuilder_.isEmpty()) {
              bodyBuilder_.dispose();
              bodyBuilder_ = null;
              body_ = other.body_;
              bitField0_ = (bitField0_ & ~0x00000002);
              bodyBuilder_ =
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getBodyFieldBuilder() : null;
            } else {
              bodyBuilder_.addAllMessages(other.body_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ProtoBufProtocol.FileCommand parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ProtoBufProtocol.FileCommand) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<Header> header_ =
        java.util.Collections.emptyList();
      private void ensureHeaderIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          header_ = new java.util.ArrayList<Header>(header_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          ProtoBufProtocol.FileCommand.Header, ProtoBufProtocol.FileCommand.Header.Builder, ProtoBufProtocol.FileCommand.HeaderOrBuilder> headerBuilder_;

      /**
       * <code>repeated .FileCommand.Header header = 1;</code>
       */
      public java.util.List<Header> getHeaderList() {
        if (headerBuilder_ == null) {
          return java.util.Collections.unmodifiableList(header_);
        } else {
          return headerBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .FileCommand.Header header = 1;</code>
       */
      public int getHeaderCount() {
        if (headerBuilder_ == null) {
          return header_.size();
        } else {
          return headerBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .FileCommand.Header header = 1;</code>
       */
      public ProtoBufProtocol.FileCommand.Header getHeader(int index) {
        if (headerBuilder_ == null) {
          return header_.get(index);
        } else {
          return headerBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .FileCommand.Header header = 1;</code>
       */
      public Builder setHeader(
          int index, ProtoBufProtocol.FileCommand.Header value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHeaderIsMutable();
          header_.set(index, value);
          onChanged();
        } else {
          headerBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .FileCommand.Header header = 1;</code>
       */
      public Builder setHeader(
          int index, ProtoBufProtocol.FileCommand.Header.Builder builderForValue) {
        if (headerBuilder_ == null) {
          ensureHeaderIsMutable();
          header_.set(index, builderForValue.build());
          onChanged();
        } else {
          headerBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .FileCommand.Header header = 1;</code>
       */
      public Builder addHeader(ProtoBufProtocol.FileCommand.Header value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHeaderIsMutable();
          header_.add(value);
          onChanged();
        } else {
          headerBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .FileCommand.Header header = 1;</code>
       */
      public Builder addHeader(
          int index, ProtoBufProtocol.FileCommand.Header value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHeaderIsMutable();
          header_.add(index, value);
          onChanged();
        } else {
          headerBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .FileCommand.Header header = 1;</code>
       */
      public Builder addHeader(
          ProtoBufProtocol.FileCommand.Header.Builder builderForValue) {
        if (headerBuilder_ == null) {
          ensureHeaderIsMutable();
          header_.add(builderForValue.build());
          onChanged();
        } else {
          headerBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .FileCommand.Header header = 1;</code>
       */
      public Builder addHeader(
          int index, ProtoBufProtocol.FileCommand.Header.Builder builderForValue) {
        if (headerBuilder_ == null) {
          ensureHeaderIsMutable();
          header_.add(index, builderForValue.build());
          onChanged();
        } else {
          headerBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .FileCommand.Header header = 1;</code>
       */
      public Builder addAllHeader(
          Iterable<? extends Header> values) {
        if (headerBuilder_ == null) {
          ensureHeaderIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, header_);
          onChanged();
        } else {
          headerBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .FileCommand.Header header = 1;</code>
       */
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          headerBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .FileCommand.Header header = 1;</code>
       */
      public Builder removeHeader(int index) {
        if (headerBuilder_ == null) {
          ensureHeaderIsMutable();
          header_.remove(index);
          onChanged();
        } else {
          headerBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .FileCommand.Header header = 1;</code>
       */
      public ProtoBufProtocol.FileCommand.Header.Builder getHeaderBuilder(
          int index) {
        return getHeaderFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .FileCommand.Header header = 1;</code>
       */
      public ProtoBufProtocol.FileCommand.HeaderOrBuilder getHeaderOrBuilder(
          int index) {
        if (headerBuilder_ == null) {
          return header_.get(index);  } else {
          return headerBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .FileCommand.Header header = 1;</code>
       */
      public java.util.List<? extends HeaderOrBuilder>
           getHeaderOrBuilderList() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(header_);
        }
      }
      /**
       * <code>repeated .FileCommand.Header header = 1;</code>
       */
      public ProtoBufProtocol.FileCommand.Header.Builder addHeaderBuilder() {
        return getHeaderFieldBuilder().addBuilder(
            ProtoBufProtocol.FileCommand.Header.getDefaultInstance());
      }
      /**
       * <code>repeated .FileCommand.Header header = 1;</code>
       */
      public ProtoBufProtocol.FileCommand.Header.Builder addHeaderBuilder(
          int index) {
        return getHeaderFieldBuilder().addBuilder(
            index, ProtoBufProtocol.FileCommand.Header.getDefaultInstance());
      }
      /**
       * <code>repeated .FileCommand.Header header = 1;</code>
       */
      public java.util.List<Header.Builder>
           getHeaderBuilderList() {
        return getHeaderFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          ProtoBufProtocol.FileCommand.Header, ProtoBufProtocol.FileCommand.Header.Builder, ProtoBufProtocol.FileCommand.HeaderOrBuilder>
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              ProtoBufProtocol.FileCommand.Header, ProtoBufProtocol.FileCommand.Header.Builder, ProtoBufProtocol.FileCommand.HeaderOrBuilder>(
                  header_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      private java.util.List<Body> body_ =
        java.util.Collections.emptyList();
      private void ensureBodyIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          body_ = new java.util.ArrayList<Body>(body_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          ProtoBufProtocol.FileCommand.Body, ProtoBufProtocol.FileCommand.Body.Builder, ProtoBufProtocol.FileCommand.BodyOrBuilder> bodyBuilder_;

      /**
       * <code>repeated .FileCommand.Body body = 2;</code>
       */
      public java.util.List<Body> getBodyList() {
        if (bodyBuilder_ == null) {
          return java.util.Collections.unmodifiableList(body_);
        } else {
          return bodyBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .FileCommand.Body body = 2;</code>
       */
      public int getBodyCount() {
        if (bodyBuilder_ == null) {
          return body_.size();
        } else {
          return bodyBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .FileCommand.Body body = 2;</code>
       */
      public ProtoBufProtocol.FileCommand.Body getBody(int index) {
        if (bodyBuilder_ == null) {
          return body_.get(index);
        } else {
          return bodyBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .FileCommand.Body body = 2;</code>
       */
      public Builder setBody(
          int index, ProtoBufProtocol.FileCommand.Body value) {
        if (bodyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBodyIsMutable();
          body_.set(index, value);
          onChanged();
        } else {
          bodyBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .FileCommand.Body body = 2;</code>
       */
      public Builder setBody(
          int index, ProtoBufProtocol.FileCommand.Body.Builder builderForValue) {
        if (bodyBuilder_ == null) {
          ensureBodyIsMutable();
          body_.set(index, builderForValue.build());
          onChanged();
        } else {
          bodyBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .FileCommand.Body body = 2;</code>
       */
      public Builder addBody(ProtoBufProtocol.FileCommand.Body value) {
        if (bodyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBodyIsMutable();
          body_.add(value);
          onChanged();
        } else {
          bodyBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .FileCommand.Body body = 2;</code>
       */
      public Builder addBody(
          int index, ProtoBufProtocol.FileCommand.Body value) {
        if (bodyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBodyIsMutable();
          body_.add(index, value);
          onChanged();
        } else {
          bodyBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .FileCommand.Body body = 2;</code>
       */
      public Builder addBody(
          ProtoBufProtocol.FileCommand.Body.Builder builderForValue) {
        if (bodyBuilder_ == null) {
          ensureBodyIsMutable();
          body_.add(builderForValue.build());
          onChanged();
        } else {
          bodyBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .FileCommand.Body body = 2;</code>
       */
      public Builder addBody(
          int index, ProtoBufProtocol.FileCommand.Body.Builder builderForValue) {
        if (bodyBuilder_ == null) {
          ensureBodyIsMutable();
          body_.add(index, builderForValue.build());
          onChanged();
        } else {
          bodyBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .FileCommand.Body body = 2;</code>
       */
      public Builder addAllBody(
          Iterable<? extends Body> values) {
        if (bodyBuilder_ == null) {
          ensureBodyIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, body_);
          onChanged();
        } else {
          bodyBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .FileCommand.Body body = 2;</code>
       */
      public Builder clearBody() {
        if (bodyBuilder_ == null) {
          body_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          bodyBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .FileCommand.Body body = 2;</code>
       */
      public Builder removeBody(int index) {
        if (bodyBuilder_ == null) {
          ensureBodyIsMutable();
          body_.remove(index);
          onChanged();
        } else {
          bodyBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .FileCommand.Body body = 2;</code>
       */
      public ProtoBufProtocol.FileCommand.Body.Builder getBodyBuilder(
          int index) {
        return getBodyFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .FileCommand.Body body = 2;</code>
       */
      public ProtoBufProtocol.FileCommand.BodyOrBuilder getBodyOrBuilder(
          int index) {
        if (bodyBuilder_ == null) {
          return body_.get(index);  } else {
          return bodyBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .FileCommand.Body body = 2;</code>
       */
      public java.util.List<? extends BodyOrBuilder>
           getBodyOrBuilderList() {
        if (bodyBuilder_ != null) {
          return bodyBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(body_);
        }
      }
      /**
       * <code>repeated .FileCommand.Body body = 2;</code>
       */
      public ProtoBufProtocol.FileCommand.Body.Builder addBodyBuilder() {
        return getBodyFieldBuilder().addBuilder(
            ProtoBufProtocol.FileCommand.Body.getDefaultInstance());
      }
      /**
       * <code>repeated .FileCommand.Body body = 2;</code>
       */
      public ProtoBufProtocol.FileCommand.Body.Builder addBodyBuilder(
          int index) {
        return getBodyFieldBuilder().addBuilder(
            index, ProtoBufProtocol.FileCommand.Body.getDefaultInstance());
      }
      /**
       * <code>repeated .FileCommand.Body body = 2;</code>
       */
      public java.util.List<Body.Builder>
           getBodyBuilderList() {
        return getBodyFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          ProtoBufProtocol.FileCommand.Body, ProtoBufProtocol.FileCommand.Body.Builder, ProtoBufProtocol.FileCommand.BodyOrBuilder>
          getBodyFieldBuilder() {
        if (bodyBuilder_ == null) {
          bodyBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              ProtoBufProtocol.FileCommand.Body, ProtoBufProtocol.FileCommand.Body.Builder, ProtoBufProtocol.FileCommand.BodyOrBuilder>(
                  body_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          body_ = null;
        }
        return bodyBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:FileCommand)
    }

    // @@protoc_insertion_point(class_scope:FileCommand)
    private static final ProtoBufProtocol.FileCommand DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ProtoBufProtocol.FileCommand();
    }

    public static ProtoBufProtocol.FileCommand getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FileCommand>
        PARSER = new com.google.protobuf.AbstractParser<FileCommand>() {
      public FileCommand parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new FileCommand(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FileCommand> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<FileCommand> getParserForType() {
      return PARSER;
    }

    public ProtoBufProtocol.FileCommand getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FileCommand_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FileCommand_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FileCommand_Header_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FileCommand_Header_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FileCommand_Body_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FileCommand_Body_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\026PortoBufProtocol.proto\"\262\001\n\013FileCommand" +
      "\022#\n\006header\030\001 \003(\0132\023.FileCommand.Header\022\037\n" +
      "\004body\030\002 \003(\0132\021.FileCommand.Body\0327\n\006Header" +
      "\022\013\n\003uri\030\001 \001(\t\022\013\n\003seq\030\002 \001(\005\022\023\n\013accessToke" +
      "n\030\003 \001(\t\032$\n\004Body\022\016\n\006buffer\030\001 \001(\014\022\014\n\004resp\030" +
      "\002 \001(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_FileCommand_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_FileCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FileCommand_descriptor,
        new String[] { "Header", "Body", });
    internal_static_FileCommand_Header_descriptor =
      internal_static_FileCommand_descriptor.getNestedTypes().get(0);
    internal_static_FileCommand_Header_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FileCommand_Header_descriptor,
        new String[] { "Uri", "Seq", "AccessToken", });
    internal_static_FileCommand_Body_descriptor =
      internal_static_FileCommand_descriptor.getNestedTypes().get(1);
    internal_static_FileCommand_Body_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FileCommand_Body_descriptor,
        new String[] { "Buffer", "Resp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
